// LOCALHOST
### Retrieve all contacts
GET http://localhost:8080/contacts

### Retrieve contact by id
GET http://localhost:8080/contacts/65ab1926ba6288f9371ae094

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Henri",
    "lastName":"Mencil",
    "email":"henomen@gmail.com",
    "favoriteColor":"green",
    "birthday":"Feb 28, 2007"
}

### PUT contact (update: add id to url)
PUT http://localhost:8080/contacts/65b478ae208de4ec8e2477e2 HTTP/1.1
content-type: application/json

{
    "firstName":"Henry",
    "lastName":"Mencl",
    "email":"henmen@gmail.com",
    "favoriteColor":"blue",
    "birthday":"February 28, 2007"
}

### DELETE contact (add id to url)
DELETE http://localhost:8080/contacts/65b4787c208de4ec8e2477e1 HTTP/1.1


// PRODUCTION Deploy
### Retrieve all contacts
GET https://test-solution2.onrender.com/contacts HTTP/1.1

### Retrieve contact by id
GET https://test-solution2.onrender.com/contacts/65ab1926ba6288f9371ae094 HTTP/1.1

### Create contact
POST https://test-solution2.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Henri",
    "lastName":"Mencil",
    "email":"henomen@gmail.com",
    "favoriteColor":"green",
    "birthday":"Feb 28, 2007"
}

### PUT contact (update: add id to url)
PUT https://test-solution2.onrender.com/contacts/65b488f1dcca11914f723ac0 HTTP/1.1
content-type: application/json

{
    "firstName":"Henry",
    "lastName":"Mencl",
    "email":"henmen@gmail.com",
    "favoriteColor":"blue",
    "birthday":"February 28, 2007"
}

### DELETE contact (add id to url)
DELETE https://test-solution2.onrender.com/contacts/65b488f1dcca11914f723ac0 HTTP/1.1